# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SampleApp3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for SampleApp3
    # Pods for OneSignalExample
    #pod 'OneSignal', '~> 1.13.3'


  target 'SampleApp3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SampleApp3-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SampleApp3-tvOS

  target 'SampleApp3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


